In [ ]:
import numpy as np
import sys

In [ ]:
l = [1, 2, 3, 4]

In [ ]:
ar = np.array(l)

In [ ]:
type(ar)

numpy.ndarray

In [ ]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [ ]:
np.asarray(l)

array([1, 2, 3, 4])

In [ ]:
a = [2, 3, 4]

In [ ]:
np.asanyarray(a)

array([2, 3, 4])

In [ ]:
b = np.matrix(l)

In [ ]:
b

matrix([[1, 2, 3, 4]])

In [ ]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [ ]:
a = np.array(l)

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
c = a

In [ ]:
c

array([1, 2, 3, 4])

In [ ]:
c[0] = 100

In [ ]:
a

array([100,   2,   3,   4])

In [ ]:
d = np.copy(a)

In [ ]:
d

array([100,   2,   3,   4])

In [ ]:
np.fromfunction(lambda i, j: i==j, (3, 3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
np.fromfunction(lambda i, j : i*j, (3, 3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [ ]:
iterable = (i*i for i in range(5))

In [ ]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [ ]:
np.fromstring('234 234', sep= ' ')

array([234., 234.])

In [ ]:
np.fromstring('2,4', sep= ',')

array([2., 4.])

In [ ]:
#Numpy - Data Types

In [ ]:
l = [2, 3, 4, 5, 6]

In [ ]:
ar = np.array(l)

In [ ]:
ar

array([2, 3, 4, 5, 6])

In [ ]:
ar.ndim

1

In [ ]:
ar2 = np.array([[1, 2, 3, 4], [2, 3, 4, 6]])

In [ ]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 6]])

In [ ]:
ar2.ndim

2

In [ ]:
ar2.size

8

In [ ]:
ar2.shape

(2, 4)

In [ ]:
ar.dtype

dtype('int64')

In [ ]:
ar2.dtype

dtype('int64')

In [ ]:
ar22 = np.array([(1.4, 45, 45), (23, 45, 66)])

In [ ]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [ ]:
ar22.dtype

dtype('float64')

In [ ]:
range(5)

range(0, 5)

In [ ]:
list(range(5))

[0, 1, 2, 3, 4]

In [ ]:
np.arange(2.3, 5.6)

array([2.3, 3.3, 4.3, 5.3])

In [ ]:
np.arange(2.3, 5.6, .3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [ ]:
list(np.arange(2.3, 5.6, .3))

[np.float64(2.3),
 np.float64(2.5999999999999996),
 np.float64(2.8999999999999995),
 np.float64(3.1999999999999993),
 np.float64(3.499999999999999),
 np.float64(3.799999999999999),
 np.float64(4.099999999999999),
 np.float64(4.399999999999999),
 np.float64(4.699999999999998),
 np.float64(4.999999999999998),
 np.float64(5.299999999999998)]

In [ ]:
np.linspace(1,5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.zeros((3, 4, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
dp = np.ones((2, 3, 2))

In [ ]:
dp + 5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.linspace(2, 4, 20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [ ]:
np.logspace(2, 5, 10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [ ]:
np.logspace(2, 5, 10, base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [ ]:
arr = np.random.rand(3, 4)

In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame(arr)

0         1         2         3
0  0.004806  0.492191  0.334954  0.751023
1  0.252872  0.093952  0.246350  0.875035
2  0.740111  0.361097  0.503264  0.139187

In [ ]:
arr = np.random.randint(1, 100, (300, 400))

In [ ]:
pd.DataFrame(arr).to_csv('test.csv')

In [ ]:
arr2 = np.random.randint(1, 100, (5,5))
arr2

array([[12, 28, 12, 22, 51],
       [33, 76, 91, 43,  9],
       [ 7, 96, 39, 50, 73],
       [63, 92, 40, 72, 40],
       [82,  3, 17, 46, 13]])

In [ ]:
arr2[arr2>50]

array([51, 76, 91, 96, 73, 63, 92, 72, 82])

In [ ]:
arr2[2:4, [1,2]]

array([[96, 39],
       [92, 40]])

In [ ]:
arr2[0][0] = 500

In [ ]:
arr2

array([[500,  28,  12,  22,  51],
       [ 33,  76,  91,  43,   9],
       [  7,  96,  39,  50,  73],
       [ 63,  92,  40,  72,  40],
       [ 82,   3,  17,  46,  13]])

In [ ]:
arr3 = np.random.randint(1, 3, (3, 3))
arr4 = np.random.randint(1, 3, (3, 3))

In [ ]:
arr3

array([[2, 2, 2],
       [1, 2, 1],
       [2, 1, 1]])

In [ ]:
arr4

array([[2, 1, 2],
       [1, 2, 1],
       [2, 2, 1]])

In [ ]:
arr3+arr4

array([[4, 3, 4],
       [2, 4, 2],
       [4, 3, 2]])

In [ ]:
arr3/arr4

array([[1. , 2. , 1. ],
       [1. , 1. , 1. ],
       [1. , 0.5, 1. ]])

In [ ]:
arr3*arr4 #index multiplication

array([[4, 2, 4],
       [1, 4, 1],
       [4, 2, 1]])

In [ ]:
arr3@arr4  #matrix multiplication

array([[10, 10,  8],
       [ 6,  7,  5],
       [ 7,  6,  6]])

In [ ]:
arr3/0

/tmp/ipython-input-1466893960.py:1: RuntimeWarning: divide by zero encountered in divide
  arr3/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [ ]:
arr3**3

array([[8, 8, 8],
       [1, 8, 1],
       [8, 1, 1]])

In [ ]:
#Numpy - Broadcasting


In [ ]:
arr5 = np.zeros((4, 4))

In [ ]:
arr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
row = np.array([1, 2, 3, 4])

In [ ]:
arr5 + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [ ]:
row.T

array([1, 2, 3, 4])

In [ ]:
col = np.array([[1, 2, 3, 4]])

In [ ]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
np.sqrt(arr5)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.exp(arr5)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.log10(arr5)

/tmp/ipython-input-3106838576.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(arr5)


array([[-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf]])