In [1]:
import numpy as np


In [2]:
arr = np.random.randint(1,10, (3,4))

In [3]:
arr

array([[7, 3, 6, 3],
       [1, 7, 6, 2],
       [4, 7, 2, 5]])

In [4]:
arr.reshpape(6,2)

AttributeError: 'numpy.ndarray' object has no attribute 'reshpape'

In [ ]:
arr.reshape(2,6)

In [5]:
arr.reshape(2, -3423)

array([[7, 3, 6, 3, 1, 7],
       [6, 2, 4, 7, 2, 5]])

In [7]:
arr.T

array([[7, 1, 4],
       [3, 7, 7],
       [6, 6, 2],
       [3, 2, 5]])

In [8]:
arr

array([[7, 3, 6, 3],
       [1, 7, 6, 2],
       [4, 7, 2, 5]])

In [9]:
arr.flatten()

array([7, 3, 6, 3, 1, 7, 6, 2, 4, 7, 2, 5])

In [11]:
arr1 = np.random.randint(1,10,12, 13, 15)

TypeError: randint() takes at most 4 positional arguments (5 given)

In [12]:
arr1.ndim

2

In [13]:
np.expand_dims(arr1, axis=1)

array([[[6, 3, 8, 7]],

       [[4, 6, 1, 4]],

       [[3, 7, 7, 1]]])

In [14]:
np.expand_dims(arr1, axis=0)

array([[[6, 3, 8, 7],
        [4, 6, 1, 4],
        [3, 7, 7, 1]]])

In [15]:
np.squeeze(arr)

array([[7, 3, 6, 3],
       [1, 7, 6, 2],
       [4, 7, 2, 5]])

In [17]:
data = np.array([[1], [2], [3]])

In [18]:
data

array([[1],
       [2],
       [3]])

In [19]:
np.squeeze(data)

array([1, 2, 3])

In [20]:
arr1

array([[6, 3, 8, 7],
       [4, 6, 1, 4],
       [3, 7, 7, 1]])

In [21]:
np.repeat(arr1, 3)

array([6, 6, 6, 3, 3, 3, 8, 8, 8, 7, 7, 7, 4, 4, 4, 6, 6, 6, 1, 1, 1, 4,
       4, 4, 3, 3, 3, 7, 7, 7, 7, 7, 7, 1, 1, 1])

In [22]:
np.roll(arr1, 2)

array([[7, 1, 6, 3],
       [8, 7, 4, 6],
       [1, 4, 3, 7]])

In [23]:
arr1

array([[6, 3, 8, 7],
       [4, 6, 1, 4],
       [3, 7, 7, 1]])

In [24]:
np.diag(arr1)

array([6, 6, 7])

In [25]:
#Numpy Binary operations

In [26]:
arr1 = np.random.randint(1,10, (3,4))

In [27]:
arr2 = np.random.randint(1,10, (3,4))

In [28]:
arr1

array([[3, 4, 5, 9],
       [2, 9, 3, 2],
       [7, 4, 1, 9]])

In [29]:
arr2

array([[8, 5, 6, 7],
       [4, 2, 3, 5],
       [4, 7, 5, 3]])

In [30]:
arr1 + arr2

array([[11,  9, 11, 16],
       [ 6, 11,  6,  7],
       [11, 11,  6, 12]])

In [31]:
arr1*arr2

array([[24, 20, 30, 63],
       [ 8, 18,  9, 10],
       [28, 28,  5, 27]])

In [32]:
arr1 & arr2

array([[0, 4, 4, 1],
       [0, 0, 3, 0],
       [4, 4, 1, 1]])

In [33]:
arr1

array([[3, 4, 5, 9],
       [2, 9, 3, 2],
       [7, 4, 1, 9]])

In [34]:
arr2

array([[8, 5, 6, 7],
       [4, 2, 3, 5],
       [4, 7, 5, 3]])

In [35]:
~arr1

array([[ -4,  -5,  -6, -10],
       [ -3, -10,  -4,  -3],
       [ -8,  -5,  -2, -10]])

In [36]:
arr1|arr2

array([[11,  5,  7, 15],
       [ 6, 11,  3,  7],
       [ 7,  7,  5, 11]])

In [37]:
arr1>arr2

array([[False, False, False,  True],
       [False,  True, False, False],
       [ True, False, False,  True]])

In [38]:
#Numpy - String Operations

In [43]:
arr = np.array(['Shiva', 'yadav'])

In [44]:
np.char.upper(arr)

array(['SHIVA', 'YADAV'], dtype='<U5')

In [45]:
np.char.capitalize(arr)

array(['Shiva', 'Yadav'], dtype='<U5')

In [46]:
# Numpy Mathmatical Operations

In [47]:
arr1

array([[3, 4, 5, 9],
       [2, 9, 3, 2],
       [7, 4, 1, 9]])

In [48]:
np.sin(arr1)

array([[ 0.14112001, -0.7568025 , -0.95892427,  0.41211849],
       [ 0.90929743,  0.41211849,  0.14112001,  0.90929743],
       [ 0.6569866 , -0.7568025 ,  0.84147098,  0.41211849]])

In [49]:
np.cos(arr1)

array([[-0.9899925 , -0.65364362,  0.28366219, -0.91113026],
       [-0.41614684, -0.91113026, -0.9899925 , -0.41614684],
       [ 0.75390225, -0.65364362,  0.54030231, -0.91113026]])

In [50]:
np.tan(arr1)

array([[-0.14254654,  1.15782128, -3.38051501, -0.45231566],
       [-2.18503986, -0.45231566, -0.14254654, -2.18503986],
       [ 0.87144798,  1.15782128,  1.55740772, -0.45231566]])

In [51]:
np.tanh(arr1)

array([[0.99505475, 0.9993293 , 0.9999092 , 0.99999997],
       [0.96402758, 0.99999997, 0.99505475, 0.96402758],
       [0.99999834, 0.9993293 , 0.76159416, 0.99999997]])

In [52]:
np.log10(arr1)

array([[0.47712125, 0.60205999, 0.69897   , 0.95424251],
       [0.30103   , 0.95424251, 0.47712125, 0.30103   ],
       [0.84509804, 0.60205999, 0.        , 0.95424251]])

In [53]:
np.exp(arr1)

array([[2.00855369e+01, 5.45981500e+01, 1.48413159e+02, 8.10308393e+03],
       [7.38905610e+00, 8.10308393e+03, 2.00855369e+01, 7.38905610e+00],
       [1.09663316e+03, 5.45981500e+01, 2.71828183e+00, 8.10308393e+03]])

In [55]:
np.sqrt(arr1)

array([[1.73205081, 2.        , 2.23606798, 3.        ],
       [1.41421356, 3.        , 1.73205081, 1.41421356],
       [2.64575131, 2.        , 1.        , 3.        ]])

In [56]:
np.power(arr1, 2)

array([[ 9, 16, 25, 81],
       [ 4, 81,  9,  4],
       [49, 16,  1, 81]])

In [58]:
np.mean(arr1)

np.float64(4.833333333333333)

In [59]:
np.median(arr1)

np.float64(4.0)

In [60]:
np.std(arr1)

np.float64(2.823512391016236)

In [62]:
np.var(arr1)

np.float64(7.972222222222222)

In [63]:
np.min(arr1)

np.int64(1)

In [64]:
np.max(arr1)

np.int64(9)