In [1]:
#sort, Search & Counting Function.


In [2]:
import numpy as np


In [3]:
arr = np.array([4, 3, 5, 6, 7, 7, 7, 3, 5, 4, 3])

In [4]:
np.sort(arr)

array([3, 3, 3, 4, 4, 5, 5, 6, 7, 7, 7])

In [5]:
np.searchsorted(arr, 5)

np.int64(2)

In [6]:
arr1 = np.array([47467, 34737, 73, 783, 83, 0, 9, 0, 93, 0])

In [7]:
np.count_nonzero(arr1)

7

In [8]:
np.where(arr>6)

(array([4, 5, 6]),)

In [9]:
np.extract(arr>6, arr)

array([7, 7, 7])

In [10]:
#Numpy - Byte Swapping


In [11]:
arr = np.array([1, 2, 3, 4, 5])

In [12]:
arr.byteswap()

array([ 72057594037927936, 144115188075855872, 216172782113783808,
       288230376151711744, 360287970189639680])

In [13]:
#Numpy - Copies & Views

In [14]:
arr

array([1, 2, 3, 4, 5])

In [15]:
a = np.copy(arr)

In [17]:
b = arr.view()

In [18]:
b

array([1, 2, 3, 4, 5])

In [19]:
b[0] = 64

In [20]:
b

array([64,  2,  3,  4,  5])

In [21]:
#Numpy - Matrix Library

In [22]:
import numpy.matlib as nm

In [23]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [24]:
nm.ones((3, 4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [26]:
#Numpy - Linear Algebra

In [27]:
arr1 = np.array([[1, 2], [3, 4]])

In [28]:
arr2 = np.array([[5, 6], [7, 8]])

In [29]:
np.dot(arr1, arr2)

array([[19, 22],
       [43, 50]])

In [30]:
arr1@arr2

array([[19, 22],
       [43, 50]])